### ISSUE TITLE
Clicking on "Ergebnisse" shows warning dialog

### ISSUE THREAD

**Issue by peckeltw** [lplotni/pace#286]
Please see screenshot.

Tested on Chrome, Firefox and Safari.
<img width="1628" alt="screen shot 2017-01-23 at 08 55 01" src="https://cloud.githubusercontent.com/assets/10725960/22195854/63b48f9e-e14a-11e6-8e90-13aa639b747c.png">

**Comment by cz8s** [comment]
Thanks a lot for reporting this.
This is tracked in trello: https://trello.com/c/k6oD0ya9/109-error-when-viewing-empty-result-list

**Comment by cz8s** [comment]
this is solved for the moment.
This was caused because the startBlocks are stored differently now and we still expect the old way on some places...
