### ISSUE TITLE
birthyear not saved

### ISSUE THREAD

**Issue by cz8s** [lplotni/pace#308]
when registering, the birthyear the participants have entered is not stored in 
the database. all rows of all participants is set to 0.

**Comment by lplotni** [comment]
I don't know what changed or why we did missed that. The PR #311 solves that. The question now is how do we get the missing information into the system. I was thinking about sending an email to all participants with the self-edit-link and ask for the birthday. What do you think @cz8s ?

**Comment by cz8s** [comment]
We will send a mail to all participants anyway. With info on when and how to pick up their start number. We will include the info that we don't have their birthdays in that mail

**Comment by lplotni** [comment]
In that case, I'll close this.
